### ISSUE TITLE
error in get query results

### ISSUE THREAD

**Issue by chmodrs** [mlabouardy/swarm-tick#1]
Hi @mlabouardy 

I'm trying to deploy tick for monitoring my production swarm cluster.

I follow your tutorial and when i create a first graph and add first query bellow:

`SELECT mean("free") AS "mean_free", mean("used") AS "mean_used", mean("total") AS "mean_total" FROM "vm_metrics"."autogen"."mem_vm" WHERE time > :dashboardTime: AND "host"=:host: GROUP BY :interval: FILL(null)`

i get a follow error

`received status code 400 from server: err: error parsing query: found :, expected identifier, string, number, bool at line 1, char 169`

i just add :hosts: variable and get node ID's, but  still get error and don't get any metric.

you have any ideia?

Thanks

**Comment by mlabouardy** [comment]
try this one 
`SELECT mean("free") AS "mean_free", mean("used") AS "mean_used", mean("total") AS "mean_total" FROM "vm_metrics"."autogen"."mem_vm" WHERE time > :dashboardTime: AND "host" = :host: GROUP BY :interval: FILL(null)`

**Comment by chmodrs** [comment]
@mlabouardy 

i put wrong temporary variable :hosts:, change for :host: and works fine!

thanks
